name: color_matcher_pro
description: A Flutter mobile application for color matching and analysis using Gemini AI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  camera: ^0.10.5
  google_generative_ai: ^0.2.3
  permission_handler: ^11.1.0
  intl: ^0.19.0
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/pantoneDb.json
